name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"  # on every midnigth

jobs:
  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "netdaemon"
#  validate_hassfest:
#    name: "Hassfest Validation"
#    runs-on: "ubuntu-latest"
#    steps:
#      - uses: "actions/checkout@v2"
#      - uses: home-assistant/actions/hassfest@master
