name: Validate with HACS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: 🏃 HACS validation
        uses: hacs/action@main
        with:
          category: netdaemon
